### ISSUE TITLE
"Fill size not multiple of 4" error at some window sizes

### ISSUE THREAD

**Issue by hrydgard** [Scthe/nanite-webgpu#2] opened 2024-09-05 18:34 UTC
Very cool stuff. However, sometimes getting this in Chrome / windows in the demos:

![image](https://github.com/user-attachments/assets/82e8f315-8fbc-492b-b77e-bf6a52305792)

Resizing the window a bit usually fixes it, so I think maybe you are filling bytes but specifying pixel count?

**Comment by Scthe** [comment] 2024-09-06 16:49
Should be fixed in https://github.com/Scthe/nanite-webgpu/commit/a562d80df3da237034bee62d97d87bce0db04967 . While I was not able to reproduce this, I had this error in the past. It's a regression introduced in https://github.com/Scthe/nanite-webgpu/commit/20f768a97df2bcbde7c9bbe02107727c0407d9c9 .

In WebGPU spec, [clearBuffer](https://www.w3.org/TR/webgpu/#dom-gpucommandencoder-clearbuffer) has `offset` and `size` parameter as optional. Both [MDN](https://developer.mozilla.org/en-US/docs/Web/API/GPUCommandEncoder/clearBuffer) and Chrome agree. Firefox's [wgpu](https://github.com/gfx-rs/wgpu) does not. It always requires 3 params.

But there is something more interesting here. On your screenshot, the size parameter is 12347125. But the buffer was [created with size](https://github.com/Scthe/nanite-webgpu/blob/master/src/passes/rasterizeSw/rasterizeSwPass.ts#L52): `BYTES_U32 * viewportSize.width * viewportSize.height`. The value for `BYTES_U32` is 4 - a number of bytes in an 32-bit unsigned int. viewport size should be positive integers. How does `4 * viewportSize.width * viewportSize.height` produce a number that ends with 5? I don't even want to investigate.

**Comment by dzaima** [comment] 2024-09-07 02:23
In the devtools console I'm seeing:
```
Viewport resize {width: 1433.6875, height: 654.3125}
```
for an error of "Fill size (3752318) is not a multiple of 4 bytes.". So width/height need some rounding somewhere.

**Comment by Scthe** [comment] 2024-09-07 04:12
(Hopefully) fixed in https://github.com/Scthe/nanite-webgpu/commit/64b5471e39c91604fa81dd098ec296a2debd17fe.

Ok, I see [where the problem is](https://github.com/Scthe/nanite-webgpu/blob/master/src/sys_web/cavasResize.ts#L45):

```js
width: canvas.clientWidth * devicePixelRatio,
height: canvas.clientHeight * devicePixelRatio,
```

[devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) is used to handle screen DPI (Retina display, etc.). It does not have to be an integer.  If you do `ctrl + scroll wheel` to zoom on a page, it will be fractional. The fix is to `Math.ceil()` the viewport dimensions. There is a better way to handle changing `devicePixelRatio`, but for now I'm more interested in fixing this.

Thanks everyone who spend their time testing and debugging this issue!

## Repro:

1.  `ctrl + scroll wheel`  to zoom on the page, which sets `devicePixelRatio` that is not an integer.
2. Refresh the page.

**Closed** 2024-11-03 19:20 UTC
